package cimeroEditor.JARGeneration;

import com.bull.cimero.pluginEditor.generator.serviceMixGenerator.model.standardModel.*;

public class SA
{
  protected static String nl;
  public static synchronized SA create(String lineSeparator)
  {
    nl = lineSeparator;
    SA result = new SA();
    nl = null;
    return result;
  }

  public final String NL = nl == null ? (System.getProperties().getProperty("line.separator")) : nl;
  protected final String TEXT_1 = "<?xml version=\"1.0\" encoding=\"UTF-8\"?>" + NL + "" + NL + "<!--" + NL + "############################################################" + NL + "    Generated by CimeroEditor" + NL + " \tBull S. A. S., Rue Jean Jaures, B.P.68, 78340, Les Clayes-sous-Bois" + NL + "############################################################" + NL + "-->" + NL + "" + NL + "" + NL + "<jbi xmlns=\"http://java.sun.com/xml/ns/jbi\" version=\"1.0\">" + NL + "\t<service-assembly>" + NL + "\t\t<identification>" + NL + "\t\t\t<name>";
  protected final String TEXT_2 = "</name>" + NL + "\t\t\t<description>";
  protected final String TEXT_3 = "</description>" + NL + "\t\t</identification>" + NL;
  protected final String TEXT_4 = "\t\t  <service-unit>" + NL + "\t\t\t<identification>" + NL + "\t\t\t\t<name>";
  protected final String TEXT_5 = "</name>" + NL + "\t\t\t\t<description>";
  protected final String TEXT_6 = "</description>" + NL + "\t\t\t</identification>" + NL + "\t\t\t<target>" + NL + "\t\t\t\t<artifacts-zip>";
  protected final String TEXT_7 = "</artifacts-zip>" + NL + "\t\t\t\t<component-name>";
  protected final String TEXT_8 = "</component-name>" + NL + "\t\t\t</target>" + NL + "\t\t</service-unit>" + NL;
  protected final String TEXT_9 = NL + "\t</service-assembly>" + NL + "</jbi>";

  public String generate(Object argument)
  {
    final StringBuffer stringBuffer = new StringBuffer();
     ServiceAssemblyClass mySA = (ServiceAssemblyClass) argument;
    stringBuffer.append(TEXT_1);
    stringBuffer.append(mySA.getServiceAssemblyName());
    stringBuffer.append(TEXT_2);
    stringBuffer.append(mySA.getServiceAssemblyDescription());
    stringBuffer.append(TEXT_3);
    		for (int i = 0; i < mySA.getLstSU().size(); i++) {
			ServiceUnitClass mySU = (ServiceUnitClass) mySA.getLstSU().get(i);

    stringBuffer.append(TEXT_4);
    stringBuffer.append(mySU.getSuName());
    stringBuffer.append(TEXT_5);
    stringBuffer.append(mySU.getSuDescription());
    stringBuffer.append(TEXT_6);
    stringBuffer.append(mySU.getSuArtifact());
    stringBuffer.append(TEXT_7);
    stringBuffer.append(mySU.getSuComponentName());
    stringBuffer.append(TEXT_8);
    		}

    stringBuffer.append(TEXT_9);
    return stringBuffer.toString();
  }
}
